#!/usr/local/bin/perl -w
use strict;
use lib './lib';
use Funknet::Config;
use Getopt::Std;

my %opt;
getopt('f', \%opt);

unless ($opt{f}) {
    print STDERR "usage: $0 -f path_to_config_file\n";
    exit(1);
}

my $config = Funknet::Config->new( configfile => $opt{f} );

# Generate the changes between current (host) and desired (whois) config.
my $bgp = $config->bgp_diff or die "bgp_diff failed: ".$config->error;
my $tun = $config->tun_diff or die "tun_diff failed: ".$config->error;

# Dump the commands generated by the diff.
print "Proposed changes:\n";
print "BGP:\n";
print $bgp->as_text;
print "\n";
print "Tunnels:\n";
print $tun->as_text;
print "\n";

# Run the commands on the local system.
#$bgp->apply;
#$tun->apply;
