package Funknet::Whois::ObjectDefs;
use strict;
#
# this file is autogenerated -- see whois_objects/generate.pl
#
use vars qw/ @EXPORT /;
@EXPORT = qw/ objectdefs /;
use base qw/ Exporter /;

sub objectdefs {

my $t = {
       'aut-num' => {
                      'source' => {
                                    'count' => 'single',
                                    'mandatory' => 'mandatory'
                                  },
                      'mnt-routes' => {
                                        'count' => 'multiple',
                                        'mandatory' => 'optional',
                                        'key' => 'inverse'
                                      },
                      'cross-nfy' => {
                                       'count' => 'multiple',
                                       'mandatory' => 'optional',
                                       'key' => 'inverse'
                                     },
                      'cross-mnt' => {
                                       'count' => 'multiple',
                                       'mandatory' => 'optional',
                                       'key' => 'inverse'
                                     },
                      'member-of' => {
                                       'count' => 'multiple',
                                       'mandatory' => 'optional',
                                       'key' => 'inverse'
                                     },
                      'tech-c' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'mandatory',
                                    'key' => 'inverse'
                                  },
                      'export' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'optional'
                                  },
                      'remarks' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'optional'
                                   },
                      'mnt-lower' => {
                                       'count' => 'multiple',
                                       'mandatory' => 'optional',
                                       'key' => 'inverse'
                                     },
                      'notify' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'optional',
                                    'key' => 'inverse'
                                  },
                      'mnt-by' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'mandatory',
                                    'key' => 'inverse'
                                  },
                      'default' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'optional'
                                   },
                      'descr' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'mandatory'
                                 },
                      'import' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'optional'
                                  },
                      'changed' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'mandatory'
                                   },
                      'admin-c' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'mandatory',
                                     'key' => 'inverse'
                                   },
                      'as-name' => {
                                     'count' => 'single',
                                     'mandatory' => 'mandatory'
                                   }
                    },
       'inet-rtr' => {
                       'source' => {
                                     'count' => 'single',
                                     'mandatory' => 'mandatory'
                                   },
                       'mnt-by' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'mandatory',
                                     'key' => 'inverse'
                                   },
                       'local-as' => {
                                       'count' => 'single',
                                       'mandatory' => 'mandatory',
                                       'key' => 'inverse'
                                     },
                       'ifaddr' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'mandatory',
                                     'key' => 'lookup'
                                   },
                       'member-of' => {
                                        'count' => 'multiple',
                                        'mandatory' => 'optional',
                                        'key' => 'inverse'
                                      },
                       'descr' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'mandatory'
                                  },
                       'tech-c' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'mandatory',
                                     'key' => 'inverse'
                                   },
                       'changed' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'mandatory'
                                    },
                       'admin-c' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'mandatory',
                                      'key' => 'inverse'
                                    },
                       'peer' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'optional'
                                 },
                       'remarks' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'optional'
                                    },
                       'notify' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'optional',
                                     'key' => 'inverse'
                                   },
                       'alias' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'optional'
                                  }
                     },
       'domain' => {
                     'source' => {
                                   'count' => 'single',
                                   'mandatory' => 'mandatory'
                                 },
                     'mnt-by' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'optional',
                                   'key' => 'inverse'
                                 },
                     'nserver' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'optional',
                                    'key' => 'inverse'
                                  },
                     'sub-dom' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'optional',
                                    'key' => 'inverse'
                                  },
                     'descr' => {
                                  'count' => 'multiple',
                                  'mandatory' => 'mandatory'
                                },
                     'tech-c' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'mandatory',
                                   'key' => 'inverse'
                                 },
                     'zone-c' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'mandatory',
                                   'key' => 'inverse'
                                 },
                     'changed' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'mandatory'
                                  },
                     'dom-net' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'optional'
                                  },
                     'admin-c' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'mandatory',
                                    'key' => 'inverse'
                                  },
                     'remarks' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'optional'
                                  },
                     'mnt-lower' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'optional',
                                      'key' => 'inverse'
                                    },
                     'notify' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'optional',
                                   'key' => 'inverse'
                                 },
                     'refer' => {
                                  'count' => 'single',
                                  'mandatory' => 'optional'
                                }
                   },
       'filter-set' => {
                         'source' => {
                                       'count' => 'single',
                                       'mandatory' => 'mandatory'
                                     },
                         'mnt-by' => {
                                       'count' => 'multiple',
                                       'mandatory' => 'mandatory',
                                       'key' => 'inverse'
                                     },
                         'filter' => {
                                       'count' => 'single',
                                       'mandatory' => 'mandatory'
                                     },
                         'descr' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'mandatory'
                                    },
                         'tech-c' => {
                                       'count' => 'multiple',
                                       'mandatory' => 'mandatory',
                                       'key' => 'inverse'
                                     },
                         'changed' => {
                                        'count' => 'multiple',
                                        'mandatory' => 'mandatory'
                                      },
                         'admin-c' => {
                                        'count' => 'multiple',
                                        'mandatory' => 'mandatory',
                                        'key' => 'inverse'
                                      },
                         'remarks' => {
                                        'count' => 'multiple',
                                        'mandatory' => 'optional'
                                      },
                         'notify' => {
                                       'count' => 'multiple',
                                       'mandatory' => 'optional',
                                       'key' => 'inverse'
                                     }
                       },
       'key-cert' => {
                       'source' => {
                                     'count' => 'single',
                                     'mandatory' => 'mandatory'
                                   },
                       'mnt-by' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'mandatory',
                                     'key' => 'inverse'
                                   },
                       'owner' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'generated'
                                  },
                       'fingerpr' => {
                                       'count' => 'single',
                                       'mandatory' => 'generated'
                                     },
                       'changed' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'mandatory'
                                    },
                       'certif' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'mandatory'
                                   },
                       'method' => {
                                     'count' => 'single',
                                     'mandatory' => 'generated'
                                   },
                       'remarks' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'optional'
                                    },
                       'notify' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'optional',
                                     'key' => 'inverse'
                                   }
                     },
       'person' => {
                     'source' => {
                                   'count' => 'single',
                                   'mandatory' => 'mandatory'
                                 },
                     'mnt-by' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'optional',
                                   'key' => 'inverse'
                                 },
                     'phone' => {
                                  'count' => 'multiple',
                                  'mandatory' => 'mandatory'
                                },
                     'nic-hdl' => {
                                    'count' => 'single',
                                    'mandatory' => 'mandatory',
                                    'key' => 'primary'
                                  },
                     'fax-no' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'optional'
                                 },
                     'e-mail' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'optional',
                                   'key' => 'lookup'
                                 },
                     'changed' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'mandatory'
                                  },
                     'address' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'mandatory'
                                  },
                     'remarks' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'optional'
                                  },
                     'notify' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'optional',
                                   'key' => 'inverse'
                                 }
                   },
       'limerick' => {
                       'source' => {
                                     'count' => 'single',
                                     'mandatory' => 'mandatory'
                                   },
                       'mnt-by' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'mandatory',
                                     'key' => 'inverse'
                                   },
                       'author' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'mandatory',
                                     'key' => 'inverse'
                                   },
                       'descr' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'optional'
                                  },
                       'changed' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'mandatory'
                                    },
                       'text' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'mandatory'
                                 },
                       'admin-c' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'mandatory',
                                      'key' => 'inverse'
                                    },
                       'remarks' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'optional'
                                    },
                       'notify' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'optional',
                                     'key' => 'inverse'
                                   }
                     },
       'route-set' => {
                        'source' => {
                                      'count' => 'single',
                                      'mandatory' => 'mandatory'
                                    },
                        'mnt-by' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'mandatory',
                                      'key' => 'inverse'
                                    },
                        'mbrs-by-ref' => {
                                           'count' => 'multiple',
                                           'mandatory' => 'optional',
                                           'key' => 'inverse'
                                         },
                        'descr' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'mandatory'
                                   },
                        'members' => {
                                       'count' => 'multiple',
                                       'mandatory' => 'optional'
                                     },
                        'tech-c' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'mandatory',
                                      'key' => 'inverse'
                                    },
                        'changed' => {
                                       'count' => 'multiple',
                                       'mandatory' => 'mandatory'
                                     },
                        'admin-c' => {
                                       'count' => 'multiple',
                                       'mandatory' => 'mandatory',
                                       'key' => 'inverse'
                                     },
                        'remarks' => {
                                       'count' => 'multiple',
                                       'mandatory' => 'optional'
                                     },
                        'notify' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'optional',
                                      'key' => 'inverse'
                                    }
                      },
       'irt' => {
                  'source' => {
                                'count' => 'single',
                                'mandatory' => 'mandatory'
                              },
                  'mnt-by' => {
                                'count' => 'multiple',
                                'mandatory' => 'mandatory',
                                'key' => 'inverse'
                              },
                  'encryption' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'mandatory'
                                  },
                  'phone' => {
                               'count' => 'multiple',
                               'mandatory' => 'optional'
                             },
                  'irt-nfy' => {
                                 'count' => 'multiple',
                                 'mandatory' => 'optional',
                                 'key' => 'inverse'
                               },
                  'tech-c' => {
                                'count' => 'multiple',
                                'mandatory' => 'mandatory',
                                'key' => 'inverse'
                              },
                  'auth' => {
                              'count' => 'multiple',
                              'mandatory' => 'mandatory'
                            },
                  'fax-no' => {
                                'count' => 'multiple',
                                'mandatory' => 'optional'
                              },
                  'e-mail' => {
                                'count' => 'multiple',
                                'mandatory' => 'mandatory',
                                'key' => 'lookup'
                              },
                  'changed' => {
                                 'count' => 'multiple',
                                 'mandatory' => 'mandatory'
                               },
                  'signature' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'mandatory'
                                 },
                  'admin-c' => {
                                 'count' => 'multiple',
                                 'mandatory' => 'mandatory',
                                 'key' => 'inverse'
                               },
                  'remarks' => {
                                 'count' => 'multiple',
                                 'mandatory' => 'optional'
                               },
                  'address' => {
                                 'count' => 'multiple',
                                 'mandatory' => 'mandatory'
                               },
                  'notify' => {
                                'count' => 'multiple',
                                'mandatory' => 'optional',
                                'key' => 'inverse'
                              }
                },
       'rtr-set' => {
                      'source' => {
                                    'count' => 'single',
                                    'mandatory' => 'mandatory'
                                  },
                      'mnt-by' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'mandatory',
                                    'key' => 'inverse'
                                  },
                      'mbrs-by-ref' => {
                                         'count' => 'multiple',
                                         'mandatory' => 'optional',
                                         'key' => 'inverse'
                                       },
                      'descr' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'mandatory'
                                 },
                      'members' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'optional'
                                   },
                      'tech-c' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'mandatory',
                                    'key' => 'inverse'
                                  },
                      'changed' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'mandatory'
                                   },
                      'admin-c' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'mandatory',
                                     'key' => 'inverse'
                                   },
                      'remarks' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'optional'
                                   },
                      'notify' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'optional',
                                    'key' => 'inverse'
                                  }
                    },
       'route' => {
                    'source' => {
                                  'count' => 'single',
                                  'mandatory' => 'mandatory'
                                },
                    'mnt-routes' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'optional',
                                      'key' => 'inverse'
                                    },
                    'aggr-bndry' => {
                                      'count' => 'single',
                                      'mandatory' => 'optional'
                                    },
                    'export-comps' => {
                                        'count' => 'single',
                                        'mandatory' => 'optional'
                                      },
                    'cross-nfy' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'optional',
                                     'key' => 'inverse'
                                   },
                    'components' => {
                                      'count' => 'single',
                                      'mandatory' => 'optional'
                                    },
                    'cross-mnt' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'optional',
                                     'key' => 'inverse'
                                   },
                    'member-of' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'optional',
                                     'key' => 'inverse'
                                   },
                    'inject' => {
                                  'count' => 'multiple',
                                  'mandatory' => 'optional'
                                },
                    'remarks' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'optional'
                                 },
                    'mnt-lower' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'optional',
                                     'key' => 'inverse'
                                   },
                    'notify' => {
                                  'count' => 'multiple',
                                  'mandatory' => 'optional',
                                  'key' => 'inverse'
                                },
                    'mnt-by' => {
                                  'count' => 'multiple',
                                  'mandatory' => 'mandatory',
                                  'key' => 'inverse'
                                },
                    'aggr-mtd' => {
                                    'count' => 'single',
                                    'mandatory' => 'optional'
                                  },
                    'holes' => {
                                 'count' => 'multiple',
                                 'mandatory' => 'optional'
                               },
                    'origin' => {
                                  'count' => 'single',
                                  'mandatory' => 'mandatory',
                                  'key' => 'primary/inverse'
                                },
                    'descr' => {
                                 'count' => 'multiple',
                                 'mandatory' => 'mandatory'
                               },
                    'changed' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'mandatory'
                                 }
                  },
       'inetnum' => {
                      'source' => {
                                    'count' => 'single',
                                    'mandatory' => 'mandatory'
                                  },
                      'mnt-routes' => {
                                        'count' => 'multiple',
                                        'mandatory' => 'optional',
                                        'key' => 'inverse'
                                      },
                      'mnt-by' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'mandatory',
                                    'key' => 'inverse'
                                  },
                      'country' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'mandatory'
                                   },
                      'netname' => {
                                     'count' => 'single',
                                     'mandatory' => 'mandatory',
                                     'key' => 'lookup'
                                   },
                      'status' => {
                                    'count' => 'single',
                                    'mandatory' => 'mandatory'
                                  },
                      'descr' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'mandatory'
                                 },
                      'tech-c' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'mandatory',
                                    'key' => 'inverse'
                                  },
                      'changed' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'mandatory'
                                   },
                      'admin-c' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'mandatory',
                                     'key' => 'inverse'
                                   },
                      'remarks' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'optional'
                                   },
                      'mnt-irt' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'optional',
                                     'key' => 'inverse'
                                   },
                      'mnt-lower' => {
                                       'count' => 'multiple',
                                       'mandatory' => 'optional',
                                       'key' => 'inverse'
                                     },
                      'notify' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'optional',
                                    'key' => 'inverse'
                                  },
                      'rev-srv' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'optional',
                                     'key' => 'inverse'
                                   }
                    },
       'as-set' => {
                     'source' => {
                                   'count' => 'single',
                                   'mandatory' => 'mandatory'
                                 },
                     'mnt-by' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'mandatory',
                                   'key' => 'inverse'
                                 },
                     'mbrs-by-ref' => {
                                        'count' => 'multiple',
                                        'mandatory' => 'optional',
                                        'key' => 'inverse'
                                      },
                     'descr' => {
                                  'count' => 'multiple',
                                  'mandatory' => 'mandatory'
                                },
                     'members' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'optional'
                                  },
                     'tech-c' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'mandatory',
                                   'key' => 'inverse'
                                 },
                     'changed' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'mandatory'
                                  },
                     'admin-c' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'mandatory',
                                    'key' => 'inverse'
                                  },
                     'remarks' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'optional'
                                  },
                     'notify' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'optional',
                                   'key' => 'inverse'
                                 }
                   },
       'inet6num' => {
                       'source' => {
                                     'count' => 'single',
                                     'mandatory' => 'mandatory'
                                   },
                       'mnt-by' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'mandatory',
                                     'key' => 'inverse'
                                   },
                       'country' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'mandatory'
                                    },
                       'netname' => {
                                      'count' => 'single',
                                      'mandatory' => 'mandatory',
                                      'key' => 'lookup'
                                    },
                       'status' => {
                                     'count' => 'single',
                                     'mandatory' => 'mandatory'
                                   },
                       'descr' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'mandatory'
                                  },
                       'tech-c' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'mandatory',
                                     'key' => 'inverse'
                                   },
                       'changed' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'mandatory'
                                    },
                       'admin-c' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'mandatory',
                                      'key' => 'inverse'
                                    },
                       'remarks' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'optional'
                                    },
                       'mnt-irt' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'optional',
                                      'key' => 'inverse'
                                    },
                       'mnt-lower' => {
                                        'count' => 'multiple',
                                        'mandatory' => 'optional',
                                        'key' => 'inverse'
                                      },
                       'notify' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'optional',
                                     'key' => 'inverse'
                                   },
                       'rev-srv' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'optional',
                                      'key' => 'inverse'
                                    }
                     },
       'tunnel' => {
                     'source' => {
                                   'count' => 'single',
                                   'mandatory' => 'mandatory'
                                 },
                     'mnt-by' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'mandatory',
                                   'key' => 'inverse'
                                 },
                     'tech-c' => {
                                   'count' => 'single',
                                   'mandatory' => 'mandatory',
                                   'key' => 'inverse'
                                 },
                     'as' => {
                               'count' => 'multiple',
                               'mandatory' => 'mandatory',
                               'key' => 'inverse'
                             },
                     'changed' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'mandatory'
                                  },
                     'admin-c' => {
                                    'count' => 'single',
                                    'mandatory' => 'mandatory',
                                    'key' => 'inverse'
                                  },
                     'type' => {
                                 'count' => 'single',
                                 'mandatory' => 'mandatory'
                               },
                     'address' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'mandatory'
                                  },
                     'notify' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'optional',
                                   'key' => 'inverse'
                                 },
                     'endpoint' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'mandatory',
                                     'key' => 'inverse'
                                   }
                   },
       'mntner' => {
                     'source' => {
                                   'count' => 'single',
                                   'mandatory' => 'mandatory'
                                 },
                     'mnt-by' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'mandatory',
                                   'key' => 'inverse'
                                 },
                     'referral-by' => {
                                        'count' => 'single',
                                        'mandatory' => 'mandatory',
                                        'key' => 'inverse'
                                      },
                     'descr' => {
                                  'count' => 'multiple',
                                  'mandatory' => 'mandatory'
                                },
                     'tech-c' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'optional',
                                   'key' => 'inverse'
                                 },
                     'auth' => {
                                 'count' => 'multiple',
                                 'mandatory' => 'mandatory'
                               },
                     'changed' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'mandatory'
                                  },
                     'admin-c' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'mandatory',
                                    'key' => 'inverse'
                                  },
                     'remarks' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'optional'
                                  },
                     'upd-to' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'mandatory',
                                   'key' => 'inverse'
                                 },
                     'notify' => {
                                   'count' => 'multiple',
                                   'mandatory' => 'optional',
                                   'key' => 'inverse'
                                 },
                     'mnt-nfy' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'optional',
                                    'key' => 'inverse'
                                  }
                   },
       'as-block' => {
                       'source' => {
                                     'count' => 'single',
                                     'mandatory' => 'mandatory'
                                   },
                       'mnt-by' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'mandatory',
                                     'key' => 'inverse'
                                   },
                       'descr' => {
                                    'count' => 'multiple',
                                    'mandatory' => 'optional'
                                  },
                       'tech-c' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'mandatory',
                                     'key' => 'inverse'
                                   },
                       'changed' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'mandatory'
                                    },
                       'admin-c' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'mandatory',
                                      'key' => 'inverse'
                                    },
                       'remarks' => {
                                      'count' => 'multiple',
                                      'mandatory' => 'optional'
                                    },
                       'notify' => {
                                     'count' => 'multiple',
                                     'mandatory' => 'optional',
                                     'key' => 'inverse'
                                   },
                       'mnt-lower' => {
                                        'count' => 'multiple',
                                        'mandatory' => 'optional',
                                        'key' => 'inverse'
                                      }
                     },
       'role' => {
                   'source' => {
                                 'count' => 'single',
                                 'mandatory' => 'mandatory'
                               },
                   'mnt-by' => {
                                 'count' => 'multiple',
                                 'mandatory' => 'optional',
                                 'key' => 'inverse'
                               },
                   'trouble' => {
                                  'count' => 'multiple',
                                  'mandatory' => 'optional'
                                },
                   'phone' => {
                                'count' => 'multiple',
                                'mandatory' => 'optional'
                              },
                   'tech-c' => {
                                 'count' => 'multiple',
                                 'mandatory' => 'mandatory',
                                 'key' => 'inverse'
                               },
                   'nic-hdl' => {
                                  'count' => 'single',
                                  'mandatory' => 'mandatory',
                                  'key' => 'primary'
                                },
                   'fax-no' => {
                                 'count' => 'multiple',
                                 'mandatory' => 'optional'
                               },
                   'e-mail' => {
                                 'count' => 'multiple',
                                 'mandatory' => 'mandatory',
                                 'key' => 'lookup'
                               },
                   'changed' => {
                                  'count' => 'multiple',
                                  'mandatory' => 'mandatory'
                                },
                   'admin-c' => {
                                  'count' => 'multiple',
                                  'mandatory' => 'mandatory',
                                  'key' => 'inverse'
                                },
                   'remarks' => {
                                  'count' => 'multiple',
                                  'mandatory' => 'optional'
                                },
                   'address' => {
                                  'count' => 'multiple',
                                  'mandatory' => 'mandatory'
                                },
                   'notify' => {
                                 'count' => 'multiple',
                                 'mandatory' => 'optional',
                                 'key' => 'inverse'
                               }
                 },
       'peering-set' => {
                          'source' => {
                                        'count' => 'single',
                                        'mandatory' => 'mandatory'
                                      },
                          'mnt-by' => {
                                        'count' => 'multiple',
                                        'mandatory' => 'mandatory',
                                        'key' => 'inverse'
                                      },
                          'peering' => {
                                         'count' => 'multiple',
                                         'mandatory' => 'mandatory'
                                       },
                          'descr' => {
                                       'count' => 'multiple',
                                       'mandatory' => 'mandatory'
                                     },
                          'tech-c' => {
                                        'count' => 'multiple',
                                        'mandatory' => 'mandatory',
                                        'key' => 'inverse'
                                      },
                          'changed' => {
                                         'count' => 'multiple',
                                         'mandatory' => 'mandatory'
                                       },
                          'admin-c' => {
                                         'count' => 'multiple',
                                         'mandatory' => 'mandatory',
                                         'key' => 'inverse'
                                       },
                          'remarks' => {
                                         'count' => 'multiple',
                                         'mandatory' => 'optional'
                                       },
                          'notify' => {
                                        'count' => 'multiple',
                                        'mandatory' => 'optional',
                                        'key' => 'inverse'
                                      }
                        }
     };

    return $t;
}
